[build-system]
requires = [
		"setuptools",
        "numpy>=1.18.0",
        "scipy>=1.6.0",
        "Cython>=0.29.0",
		"mkl>=2021.3.0",
		"mkl-include>=2021.3.0",
        ]
build-backend = "setuptools.build_meta"
